CLASS zcl_test_event_001_vn DEFINITION
  PUBLIC
  FINAL FOR EVENTS OF i_salesordertp
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_TEST_EVENT_001_VN IMPLEMENTATION.
ENDCLASS.
