CLASS zcl_rap_fun_vf006_02 DEFINITION
  PUBLIC
  FINAL FOR EVENTS OF i_supplierinvoicetp
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_RAP_FUN_VF006_02 IMPLEMENTATION.
ENDCLASS.
